name: Odoo Backup

# Trigger di esecuzione del workflow
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # Esecuzione programmata (ogni giorno alle 2:00 AM)
  
jobs:
    backup:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        


        - name: Setup SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            
          run:
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            touch ~/.ssh/known_hosts
            ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            ssh -p 23 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} echo "Connessione riuscita"


            