name: Odoo Backup

# Trigger di esecuzione del workflow
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # Esecuzione programmata (ogni giorno alle 2:00 AM)
  
jobs:
    backup:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Setup SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > base64 -d > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa

        - name: Genera know_hosts
          run: |
           echo "Configurazione manuale di known_hosts"
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_HOST }} $(ssh-keygen -f /dev/null -l -E md5 2>/dev/null)" >> ~/.ssh/known_hosts
           echo "Host ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
           echo "  Port 23" >> ~/.ssh/config
           echo "  StrictHostKeyChecking no" >> ~/.ssh/config

        - name: Test connessione SSH
          run: ssh -o StrictHostKeyChecking=no -T ${{ secrets.SSH_HOST }} || exit 1
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}

        - name: Debug
          run: cat ~/.ssh/known_hosts
