name: Odoo Backup

# Trigger di esecuzione del workflow
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # Esecuzione programmata (ogni giorno alle 2:00 AM)
  
jobs:
    backup:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Preparazione alla connessione
          run: |
            # Generazione automatica della entry known_hosts
            echo "Generazione automatica del file known_hosts per ${{ secrets.SERVER_IP }}"
            ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            # Verifica configurazione
            ls -la ~/.ssh
            
            echo "Connessione al server ${{ secrets.SERVER_IP }} come utente ${{ secrets.SSH_USER }}"
