name: Odoo Backup

# Trigger di esecuzione del workflow
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # Esecuzione programmata (ogni giorno alle 2:00 AM)
  
jobs:
    backup:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Setup SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > base64 -d > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa

        - name: Genera know_hosts
          run: |
           echo "Configurazione manuale di known_hosts"
           

        - name: Test connessione SSH
          run: |
            "echo 'Qui la gestione della connessione SSH'"
